#safelist
branches:
  only:
   -master

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for log
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed icedevs001/udagram-api-feed:v1
  - docker tag udagram-api-user icedevs001/udagram-api-user:v1
  - docker tag udagram-frontend:local icedevs001/udagram-frontend:v1
  - docker tag reverseproxy icedevs001/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push icedevs001/udagram-api-feed:v1
  - docker push icedevs001/udagram-api-user:v1
  - docker push icedevs001/udagram-frontend:v1
  - docker push icedevs001/reverseproxy:v1


