apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
  labels:
    app: api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      run: api-feed
  template:
    metadata:
      labels:
        run: api-feed
    spec:
      containers:
      - name: api-feed
        image: icedevs001/udagram-api-feed:v2
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 700m
          requests:
            cpu: 400m

---
apiVersion: v1
kind: Service
metadata:
  name: api-feed-svc
  labels:
    run: api-feed
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: api-feed