apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: icedevs001/udagram-frontend:v18
        ports:
        - containerPort: 80
        resources:
          limits: 
            cpu: 500m
          requests:
            cpu: 250m
        env:
        # Define the environment variable
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ice-aws-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ice-aws-secret
              key: aws_secret_access_key
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: ice-pg-secret
              key: postgres_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ice-pg-secret
              key: postgres_password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: ice-configmap
              key: postgres_host
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ice-configmap
              key: postgres_db
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: ice-configmap
              key: aws_bucket
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: ice-configmap
              key: aws_region
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: ice-configmap
              key: aws_profile
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: ice-configmap
              key: jwt_secret
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: ice-configmap
              key: url

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    run: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: frontend