apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: icedevs001/udagram-frontend:v2
        ports:
        - containerPort: 8080
        resources:
          limits: 
            cpu: 500m
          requests:
            cpu: 250m

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    run: frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: frontend